### ISSUE TITLE
Clean Entities - error with deleted entities during tests

### ISSUE THREAD

**Issue by lpeidro** [Metadrop/behat-contexts#121]
"Clean Entities" fails after scenarios where there are entities that are eliminated for being dependent on other entities. 

For example when there is a child entity and another parent, and the child entity cannot exist without the parent entity.

Solution: check if entity exists before being delete.

**Comment by mistermoper** [comment]
@lpeidro solved in the v1.6.1 version. Now the entity delete is safe when the entity has been deleted in other ways.
