### ISSUE TITLE
Deprecated function file_save_data()

### ISSUE THREAD

**Issue by albeorte96** [Metadrop/behat-contexts#147]
As of drupal:9.3.0 and is removed from drupal:10.0.0. 
Use` \Drupal\file\FileRepositoryInterface::writeData` instead.

https://api.drupal.org/api/drupal/core%21modules%21file%21file.module/function/file_save_data/9

**Comment by mistermoper** [comment]
For this issue, there exists a pull request that Ortega created: https://github.com/Metadrop/behat-contexts/pull/148.  At that moment I reviewed it and gave feedback https://github.com/Metadrop/behat-contexts/pull/148/files#r1115723333 With the proposed solution, the code will be compatible with Drupal 8 or higher.

**Comment by mistermoper** [comment]
Fixed in https://github.com/Metadrop/behat-contexts/pull/168 and released in v1.13.55, thanks both!
